name: kubefarm
description: Kubefarm cluster
version: 0.5.2
appVersion: 1.19.0
icon: https://avatars1.githubusercontent.com/u/68351149?s=150&u=b8b4cb0f364281274159d4098090c0e229370cf0
keywords:
  - kubernetes
  - ltsp
home: https://github.com/kvaps/kubefarm
sources:
  - https://github.com/kvaps/kubefarm
maintainers:
  - name: kvaps
    email: kvapss@gmail.com
dependencies:
  - name: kubernetes
    version: 0.5.2
    condition: kubernetes.enabled
